### ISSUE TITLE
kaldi-android

### ISSUE THREAD

**Issue by LqNoob** [funcwj/kaldi-enhan#1]
Hi，我读了你的博客文章——《在安卓上使用kaldi进行模型开发 》，但是没有发现你是如何在Android端使用kaldi的nnet和feat模块。目前，我想在android端使用kaldi的译码模块，但是很少的资料谈到这一块。
不知道方不方便看看你是如何调用nnet和feat模块的？
谢谢！

**Comment by funcwj** [comment]
怎么调需要你熟悉相关模块中一些基本函数的功能，kaldi里面代码比较规范，注释也写的挺全，功能清楚之后，函数调用并不难。

**Comment by LqNoob** [comment]
你好！译码模块已经看啦，jni如何调用so文件也已经看啦，但是对如何调用译码模块还不是很懂，所以想参考一下你是如何调用kaldi的nnet和feat模块的。
谢谢啦！

**Comment by funcwj** [comment]
这个是很早以前的工作，现在代码也不在身边，你留个邮箱，后面和你联系。

**Comment by LqNoob** [comment]
好的，谢谢啦！我的邮箱是1944189618@qq.com
