### ISSUE TITLE
usage of this repository

### ISSUE THREAD

**Issue by ffxz** [funcwj/kaldi-enhan#4]
the SE project using kaldi seems good, if you can provide the detail of usage, that sounds perfect.

**Comment by funcwj** [comment]
This repo was originally derived from my works on speech enhancement tasks. I would like to given some pipeline, like egs in kaldi, but do not have much time now, may be in the feture such instructions will coming, when time is availble.

**Comment by funcwj** [comment]
In fact, I think it's not difficult for someone who has experience on speech enhancement to know the usage of each command or script, see notations or references in the code.
